version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: osims-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zC(937<wM9Ce
      POSTGRES_DB: osimsdev
    ports:
      - "5432:5432"
    volumes:
      - db_local_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: osims-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 4678U@)6w?Fp
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  db_local_data:
